// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CpeUIClient is the client API for CpeUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CpeUIClient interface {
	// ListDcimSpecs returns a list of Data Center Infrastructure Manager(s) that can be started through the UI.
	ListDcimSpecs(ctx context.Context, in *ListDcimSpecsRequest, opts ...grpc.CallOption) (CpeUI_ListDcimSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type cpeUIClient struct {
	cc grpc.ClientConnInterface
}

func NewCpeUIClient(cc grpc.ClientConnInterface) CpeUIClient {
	return &cpeUIClient{cc}
}

func (c *cpeUIClient) ListDcimSpecs(ctx context.Context, in *ListDcimSpecsRequest, opts ...grpc.CallOption) (CpeUI_ListDcimSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CpeUI_ServiceDesc.Streams[0], "/v1.CpeUI/ListDcimSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &cpeUIListDcimSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CpeUI_ListDcimSpecsClient interface {
	Recv() (*ListDcimSpecsResponse, error)
	grpc.ClientStream
}

type cpeUIListDcimSpecsClient struct {
	grpc.ClientStream
}

func (x *cpeUIListDcimSpecsClient) Recv() (*ListDcimSpecsResponse, error) {
	m := new(ListDcimSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cpeUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.CpeUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CpeUIServer is the server API for CpeUI service.
// All implementations must embed UnimplementedCpeUIServer
// for forward compatibility
type CpeUIServer interface {
	// ListDcimSpecs returns a list of Data Center Infrastructure Manager(s) that can be started through the UI.
	ListDcimSpecs(*ListDcimSpecsRequest, CpeUI_ListDcimSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedCpeUIServer()
}

// UnimplementedCpeUIServer must be embedded to have forward compatible implementations.
type UnimplementedCpeUIServer struct {
}

func (UnimplementedCpeUIServer) ListDcimSpecs(*ListDcimSpecsRequest, CpeUI_ListDcimSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDcimSpecs not implemented")
}
func (UnimplementedCpeUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedCpeUIServer) mustEmbedUnimplementedCpeUIServer() {}

// UnsafeCpeUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CpeUIServer will
// result in compilation errors.
type UnsafeCpeUIServer interface {
	mustEmbedUnimplementedCpeUIServer()
}

func RegisterCpeUIServer(s grpc.ServiceRegistrar, srv CpeUIServer) {
	s.RegisterService(&CpeUI_ServiceDesc, srv)
}

func _CpeUI_ListDcimSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDcimSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CpeUIServer).ListDcimSpecs(m, &cpeUIListDcimSpecsServer{stream})
}

type CpeUI_ListDcimSpecsServer interface {
	Send(*ListDcimSpecsResponse) error
	grpc.ServerStream
}

type cpeUIListDcimSpecsServer struct {
	grpc.ServerStream
}

func (x *cpeUIListDcimSpecsServer) Send(m *ListDcimSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CpeUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpeUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.CpeUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpeUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CpeUI_ServiceDesc is the grpc.ServiceDesc for CpeUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CpeUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.CpeUI",
	HandlerType: (*CpeUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _CpeUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDcimSpecs",
			Handler:       _CpeUI_ListDcimSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cpe-ui.proto",
}
